app/about_me/__init__.py
from flask import Blueprint

about = Blueprint("about", __name__, template_folder="templates")


from . import views

app/about_me/views.py
from flask import render_template
from . import about

my_soft_skills = ["communication", "hard-working", "polite"]

my_hard_skills = ["Java", "Spring", "OOD", "Rest api", "MySql", "Postgresql", "Python", "Php", "C++", "JavaScript"]


@about.route('/about')
def about_page():
    return render_template("about.html")


@about.route('/soft_skills', defaults={'idx': None})
@about.route('/soft_skills/<int:idx>')
def soft_skills(idx):
    if idx is None:
        return render_template("soft-skills.html", soft_skills=my_soft_skills)
    elif 0 < idx <= len(my_soft_skills):
        return render_template("skill.html", skill=my_soft_skills[idx-1], index=idx, soft_skills=my_soft_skills)
    else:
        return "Skill not found"


@about.route('/hard_skills', defaults={'idx': None})
@about.route('/hard_skills/<int:idx>')
def hard_skills(idx):
    if idx is None:
        return render_template("hard-skills.html", hard_skills=my_hard_skills)
    elif 0 < idx <= len(my_hard_skills):
        return render_template("skill.html", skill=my_hard_skills[idx-1], index=idx, hard_skills=my_hard_skills)
    else:
        return "Skill not found"

app/about_me/templates/about.html
{% extends "/other/base.html" %}
{% block title %} <title>about</title> {% endblock %}
{% block content %}
    <div class="centered p-4 pt-0">
        <h1 class="fst-italic">About me</h1>
        <img src="{{ url_for('static', filename='images/me.jpg') }}" height="200px"><br>
        <h4 class="fst-italic pt-2">Hello, my name is Marian and I study at Vasyl Stefanyk Precarpathian University at the Faculty of Mathematics and Informatics. My hobby is singing, I am singing 13 years. I have a lot of <a href="{{ url_for('about.soft_skills') }}">soft skills</a> and <a href="{{ url_for('about.hard_skills') }}">hard skills</a>. I have six web-applications written on TypeScript with Nextjs framework. All of them you can see on my GitHub.</h4><br>
    </div>
{% endblock %}
{% block marg %}
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}
{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchahsyi</p>
    </div>
{% endblock %}

app/about_me/templates/hard-skills.html
{% extends "/other/base.html" %}

{% block title %}<title>Hard skills</title>{% endblock %}

{% block content %}
    <div class="container">
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
                <ul>
                    <h1>My hard skills</h1>
                    {% for i in hard_skills %}
                        <li class="fst-italic"><a class="p-2 link-secondary" href="{{ url_for('about.hard_skills', idx=loop.index) }}">{{ i }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}
{% block marg %}
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}

{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchashyi</p>
    </div>
{% endblock %}

app/about_me/templates/skill.html
{% extends "/other/base.html" %}
{% block title %}<title>Skill</title>{% endblock %}
{% block content %}
    <div class="container">
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
                <ul>
                    <h1>My skill with number {{ index }}</h1>

                        <h2>{{ skill }}</h2>
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}
{% block marg %}
    <div class="marg"></div>
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}
{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchashyi</p>
    </div>
{% endblock %}

app/about_me/templates/soft-skills.html
{% extends "/other/base.html" %}

{% block title %}<title>Soft skills</title>{% endblock %}

{% block content %}
    <div class="container">
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
                <ul>
                    <h1>My soft skills</h1>
                    {% for i in soft_skills %}
                        <li class="fst-italic"><a class="p-2 link-secondary" href="{{ url_for('about.soft_skills', idx=loop.index) }}">{{ i }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}
{% block marg %}
    <div class="marg"></div>
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}
{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchashyi</p>
    </div>
{% endblock %}