app/post/models.py
from app import db
import enum


class Type(enum.Enum):
    news = 1
    publication = 2
    other = 3


tags = db.Table('post_tags',
                db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')))


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False, unique=True)

    @staticmethod
    def get_or_create(name):
        tag = Tag.query.filter_by(name=name).first()
        if tag:
            return tag
        else:
            new_tag = Tag(name=name)
            db.session.add(new_tag)
            db.session.commit()
            return new_tag


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False, unique=True)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    text = db.Column(db.String)
    image = db.Column(db.String, default='static/images/Me')
    created = db.Column(db.TIMESTAMP, server_default=db.func.current_timestamp(), nullable=False)
    type = db.Column(db.Enum(Type), default='news', nullable=False)
    enabled = db.Column(db.Boolean, default=True, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id', name='fk_post_category'), nullable=True)
    category = db.relationship('Category', backref='posts')
    tags = db.relationship('Tag', secondary=tags, backref='posts')

    def __repr__(self):
        return f"<Post {self.id}, Title: {self.title}, Type: {self.type}, Enabled: {self.enabled}>"

app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, FileField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    image = FileField('Profile Image')
    type = SelectField('Type', choices=[('news', 'News'), ('publication', 'Publication'), ('other', 'Other')], validators=[DataRequired()])
    category = SelectField('Category', coerce=int)
    tags = StringField('Tags')
    submit = SubmitField('Submit')


class UpdateForm(FlaskForm):
    title = StringField('Title')
    text = TextAreaField('Text')
    image = FileField('Profile Image')
    type = SelectField('Type', choices=[('news', 'News'), ('publication', 'Publication'), ('other', 'Other')])
    category = SelectField('Category', coerce=int)
    tags = StringField('Tags')
    submit = SubmitField('Submit')


class DeleteForm(FlaskForm):
    submit = SubmitField('Delete post')


class CategoryForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/post/__init__.py
from flask import Blueprint

post = Blueprint("post", __name__, template_folder="templates")


from . import views

app/post/views.py
import time

from flask import render_template, redirect, url_for, request
from flask_login import current_user
from werkzeug.utils import secure_filename
from . import post
from .forms import PostForm, DeleteForm, CategoryForm, UpdateForm
from .models import db, Post, Category, Tag


@post.route('/post/create', methods=['GET', 'POST'])
def create_post():
    if current_user.is_authenticated:
        form = PostForm()
        categories = Category.query.all()
        form.category.choices = [(category.id, category.name) for category in categories]
        if form.validate_on_submit() or request.method == 'POST':
            profile_image = form.image.data
            if profile_image:
                filename = secure_filename(profile_image.filename)
                unique_filename = f"{int(time.time())}_{filename}.jpg"
                file_path = f'images/{unique_filename}'
                profile_image.save(f'app/static/{file_path}')
            tags = form.tags.data.split(',')
            tags = [tag.strip() for tag in tags if tag]
            category_id = form.category.data
            category = Category.query.get(category_id)
            new_post = Post(
                title=form.title.data,
                text=form.text.data,
                type=form.type.data,
                image=file_path if profile_image else None,
                user_id=current_user.id,
                category=category,
                tags=[Tag.get_or_create(tag) for tag in tags]
            )
            db.session.add(new_post)
            db.session.commit()
            return redirect(url_for('post.list_posts'))
    else:
        return redirect(url_for('auth.choice'))
    return render_template('create_post.html', form=form, categories=categories)


@post.route('/post', methods=['GET'])
def list_posts():
    page = request.args.get('page', 1, type=int)
    per_page = 5
    all_posts = Post.query.order_by(Post.created.desc()).paginate(page=page, per_page=per_page)
    return render_template('list_posts.html', posts=all_posts)


@post.route('/post/<int:id>', methods=['GET'])
def view_post(id):
    del_form = DeleteForm()
    post = Post.query.get(id)
    return render_template('view_post.html', post=post, del_form=del_form)


@post.route('/post/<int:id>/update', methods=['POST', 'GET'])
def update_post(id):
    categories = Category.query.all()
    post = Post.query.get(id)
    form = UpdateForm()
    form.category.choices = [(category.id, category.name) for category in categories]
    if form.validate_on_submit() or request.method == 'POST':
        if form.title.data:
            post.title = form.title.data
        if form.text.data:
            post.text = form.text.data
        if form.type.data:
            post.type = form.type.data
        if form.tags.data:
            tags = form.tags.data.split(',')
            tags = [tag.strip() for tag in tags if tag]
            post.tags = [Tag.get_or_create(tag) for tag in tags]
        if form.category.data:
            category_id = form.category.data
            category = Category.query.get(category_id)
            post.category = category
        profile_image = form.image.data
        if profile_image:
            filename = secure_filename(profile_image.filename)
            unique_filename = f"{int(time.time())}_{filename}.jpg"
            file_path = f'images/{unique_filename}'
            profile_image.save(f'app/static/{file_path}')
            post.image = file_path
        db.session.commit()
        return redirect(url_for('post.list_posts'))
    elif request.method == 'GET':
        form.title.data = post.title
        form.text.data = post.text
        form.type.data = post.type
        form.category.data = post.category
        form.tags.data = post.tags
    return render_template('update_post.html', form=form, post=post, categories=categories)


@post.route('/post/<int:id>/delete', methods=['POST'])
def delete_post(id):
    if request.method == 'POST':
        post = Post.query.get(id)
        db.session.delete(post)
        db.session.commit()
    return redirect(url_for('post.list_posts'))


@post.route('/categories', methods=['GET'])
def list_categories():
    categories = Category.query.all()
    return render_template('list_categories.html', categories=categories)


@post.route('/categories/create', methods=['GET', 'POST'])
def create_category():
    form = CategoryForm()
    if form.validate_on_submit() or request.method == 'POST':
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        return redirect(url_for('post.list_categories'))
    return render_template('create_category.html', form=form)

app/post/templates/create_category.html
{% extends "other/base.html" %}
{% block title %} <title>Category</title> {% endblock %}
{% block content %}
{% from "other/macros.html" import render_field %}
    <div class="centered2 p-4">
    <h2>Category page</h2>
    <form action="{{ url_for('post.create_category') }}" method="post" class="row g-3" enctype="multipart/form-data" novalidate>
        <div class="form-outline">
            {{ form.hidden_tag() }}
            {{ render_field(form.name, class="form-control") }}<br>
            {{ form.submit(class="btn btn-primary mb-3 bg-dark", label="update")}}
        </div>
    </form>
    </div>
{% endblock %}
{% block marg %}
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}
{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchashyi</p>
    </div>
{% endblock %}

app/post/templates/create_post.html
{% extends "other/base.html" %}
{% block title %} <title>Post</title> {% endblock %}
{% block content %}
{% from "other/macros.html" import render_field %}
    <div class="centered2 p-4">
    <h2>Post page</h2>
    <form action="{{ url_for('post.create_post') }}" method="post" class="row g-3" enctype="multipart/form-data" novalidate>
        <div class="form-outline">
            {{ form.hidden_tag() }}
            {{ render_field(form.title, class="form-control") }}<br>
            {{ render_field(form.text, class="form-control") }}<br>
            {{ render_field(form.image, class="form-control") }}<br>
            {{ render_field(form.type, class="form-control") }}<br>
            {{ render_field(form.category, class="form-control") }}<br>
            {{ render_field(form.tags, class="form-control") }}<br>
            {{ form.submit(class="btn btn-primary mb-3 bg-dark", label="update")}}
        </div>
    </form>
    <h2>List of Categories</h2>
    <ul>
        {% for category in categories %}
            <h3><li>{{ category.name }}</li></h3>
        {% endfor %}
    </ul>
    </div>
{% endblock %}
{% block marg %}
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}
{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchashyi</p>
    </div>
{% endblock %}

app/post/templates/list_categories.html
{% extends "other/base.html" %}
{% block title %} <title>Categories</title> {% endblock %}
{% block content %}
<div class="container p-4">
    <h2>List of Categories</h2>
    <ul>
        {% for category in categories %}
            <h3><li>{{ category.name }}</li></h3>
        {% endfor %}
    </ul>
 <h2><a href="{{ url_for('post.create_category') }}">Create new category</a></h2>
</div>

{% endblock %}
{% block marg %}
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}
{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchashyi</p>
    </div>
{% endblock %}

app/post/templates/list_posts.html
{% extends "other/base.html" %}
{% block title %} <title>Post</title> {% endblock %}
{% block content %}
<div class="container p-4">
    <h2>List of Posts</h2>
    <ul>
        {% for post in posts %}
            <h4><li><a href="{{ url_for('post.view_post', id=post.id) }}">{{ post.title }}</a>->{{ post.type }}->{{ post.enabled }}</li></h4>
        {% endfor %}
    </ul>
</div>
{% endblock %}
{% block marg %}
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}
{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchashyi</p>
    </div>
{% endblock %}

app/post/templates/update_post.html
{% extends "other/base.html" %}
{% block title %} <title>Post</title> {% endblock %}
{% block content %}
{% from "other/macros.html" import render_field %}
    <div class="centered2 p-4">
    <h2>Update page</h2>
    <form action="{{ url_for('post.update_post', id=post.id) }}" method="post" class="row g-3" enctype="multipart/form-data" novalidate>
        <div class="form-outline">
            {{ form.hidden_tag() }}
            {{ render_field(form.title, class="form-control") }}<br>
            {{ render_field(form.text, class="form-control") }}<br>
            {{ render_field(form.image, class="form-control") }}<br>
            {{ render_field(form.type, class="form-control") }}<br>
            {{ render_field(form.category, class="form-control") }}<br>
            {{ render_field(form.tags, class="form-control") }}<br>
            {{ form.submit(class="btn btn-primary mb-3 bg-dark", label="update")}}
        </div>
    </form>
    <h2>List of Categories</h2>
    <ul>
        {% for category in categories %}
            <h3><li>{{ category.name }}</li></h3>
        {% endfor %}
    </ul>
    </div>
{% endblock %}
{% block marg %}
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}
{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchashyi</p>
    </div>
{% endblock %}

app/post/templates/view_post.html
{% extends "other/base.html" %}
{% block title %} <title>Post</title> {% endblock %}
{% block content %}
<div class="centered2 p-4">
  <h2>{{ post.title }}</h2>
  <img src="{{url_for('static', filename=post.image) }}" width="300px">
  <p>{{ post.text }}</p>
  <p>type: {{ post.type }}</p>
  <p>created: {{ post.created }}</p>
  <p>enabled: {{ post.enabled }}</p>
  <p>user_id : {{ post.user_id }}</p>
  <p>tags: {{ post.tags }}</p>
  <p>category : {{ post.category }}</p>
  {% if current_user.is_authenticated and post.user_id == current_user.id %}
    <button class="btn btn-primary mb-3 bg-light"><a href="{{ url_for('post.update_post', id=post.id) }}">Edit post</a></button>
    <form method="POST" action="{{ url_for('post.delete_post', id=post.id) }}" class="row g-3">
      <div class="form-outline">
            {{ del_form.hidden_tag() }}
            {{ del_form.submit(class="btn btn-danger ms-1", label="update")}}
        </div>
    </form>
  {% endif %}
    </div>
{% endblock %}
{% block marg %}
    <span class="centered2 p-4"><a href="{{ url_for('appb.base') }}" class="fst-italic link-secondary text-dark">Base page</a></span>
{% endblock %}
{% block footer %}
    <div>
        <p class="display-10 fst-italic">@marian_pidchashyi</p>
    </div>
{% endblock %}